export const keyTransforms = {
  PromotionId: "promotion_id",
  PromotionID: "promotion_id",
  PromotionDescription: "promotion_description",
  PriceUpdateDate: "promotion_update_date",
  PromotionUpdateDate: "promotion_update_date",
  PromotionStartDate: "promotion_start_date",
  PromotionStartHour: "promotion_start_hour",
  PromotionEndDate: "promotion_end_date",
  PromotionEndHour: "promotion_end_hour",
  RewardType: "reward_type",
  AllowMultipleDiscounts: "allow_multiple_discounts",
  IsWeightedPromo: "is_weighted_promo",
  MinQty: "min_qty",
  DiscountedPrice: "discounted_price",
  DiscountedPricePerMida: "discounted_price_per_mida",
  MinNoOfItemOfered: "min_no_of_items_offered",
  MinNoOfItemsOffered: "min_no_of_items_offered",
  WeightUnit: "weight_unit",
  ItemType: "item_type",
  ItemCode: "item_code",
  IsGiftItem: "is_gift_item",
  AdditionalIsCoupon: "additional_is_coupon",
  AdditionalsCoupon: "additional_is_coupon",
  AdditionalGiftCount: "additional_gift_count",
  AdditionalsGiftCount: "additional_gift_count",
  AdditionalIsTotal: "additional_is_total",
  AdditionalsTotals: "additional_is_total",
  AdditionalIsActive: "additional_is_active",
  ClubId: "club_id",
  ClubID: "club_id",
  //   bitan and mega not included
  DiscountRate: "discount_rate",
  DiscountType: "discount_type",
  MaxQty: "max_qty",
  MAXQTY: "max_qty",
  MinPurchaseAmount: "min_purchase_amount",
  AdditionalsMinBasketAmount: "additionals_min_basket_amount",
};

export const integerKeys = [
  "reward_type",
  "allow_multiple_discounts",
  "is_weighted_promo",
  "additional_is_coupon",
  "additional_gift_count",
  "additional_is_total",
  "additional_is_active",
  "min_no_of_items_offered",
  "weight_unit",
  "item_type",
  "is_gift_item",
  "discount_rate",
  "discount_type",
  "max_qty",
  "min_purchase_amount",
  "club_id",
];

export const floatsKeys = ["min_qty", "max_qty", "discounted_price", "discounted_price_per_mida"];
